apiVersion: mediastreams.media-streaming-mesh.io/v1
kind: Streamdata
metadata:
  labels:
    app.kubernetes.io/name: streamdata
    app.kubernetes.io/instance: streamdata-sample
    app.kubernetes.io/part-of: msm-nc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: msm-nc
  name: streamdata-sample
  namespace: msm-nc-system
spec:
  stubip: 172.0.0.0
  serverip: 192.168.1.0
  clientip: 0.0.0.0
  serverport: 80
  clientport: 8080
  streamstate: play
